dataroot: ./data-train/
checkpoint_path: checkpoint
name: selfatt

batchsize: 16
epochs: 10
lr: 0.0002
lr_milestone:
  - 5

phase: pretrain

resize: 256
hflip: true
URange: 256
VRange: 256

display_freq: 500

body_nc: 26

G:
  nf: 32                      # number of base filters in the generator
  n_res_blks: 5               # number of residual blocks in content encoder/decoder
  latent_dim: 64              # dimension of the latent code for the class model
  n_downs_content: 4          # number of downsampling layers in content encoder
  n_downs_class: 4            # number of downsampling layers in class model encoder
  input_dim: 26

