dataroot: ./data-train/
checkpoint_path: checkpoint
name: selfatt

batchsize: 10
epochs: 15
lr: 0.0002
lr_T: 0.0002
lr_D: 0.0002
lr_milestone:
  - 5
  - 10

phase: train
pretrain_name: latest

resize: 256
texture_size: 128
hflip: true
URange: 256
VRange: 256

display_freq: 500

body_nc: 26

G:
  nf: 32                      # number of base filters in the generator
  n_res_blks: 5               # number of residual blocks in content encoder/decoder
  nf_mlp: 256                 # number of base filters in MLP module
  latent_dim: 64              # dimension of the latent code for the class model
  n_mlp_blks: 3               # number of mlp blocks
  n_downs_content: 4          # number of downsampling layers in content encoder
  n_downs_class: 4            # number of downsampling layers in class model encoder
  input_dim: 26

Texture_G:
  nf: 64                      # number of base filters in the generator
  n_res_blks: 6               # number of residual blocks in content encoder/decoder
  n_downs: 3                  # number of downsampling layers in content encoder
  input_dim: 72
  output_dim: 72

num_texture: 8
l_texture: 1.0
l_coordinate: 20.0
l_mask: 0.8
l_vgg: 1.0
